// Generated by: neuraforge-ai / nestjs-forge
// Thin controller — validation via DTOs, logic in service

import {
  Controller, Get, Post, Put, Delete,
  Param, Body, Query, ParseIntPipe,
  UseGuards, Request, HttpCode, HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOkResponse } from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { OrdersService } from './orders.service';
import { CreateOrderDto } from './dto/create-order.dto';
import { UpdateOrderDto } from './dto/update-order.dto';
import { PaginationDto } from '../common/dto/pagination.dto';
import { PagedResponse } from '../common/types/paged-response.type';
import { OrderDto } from './dto/order.dto';

@ApiTags('orders')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller('api/v1/orders')
export class OrdersController {
  constructor(private readonly ordersService: OrdersService) {}

  @Get()
  @ApiOkResponse({ type: PagedResponse<OrderDto> })
  getAll(@Query() pagination: PaginationDto): Promise<PagedResponse<OrderDto>> {
    return this.ordersService.getAll(pagination);
  }

  @Get(':orderId')
  getById(@Param('orderId', ParseIntPipe) orderId: number): Promise<OrderDto> {
    return this.ordersService.getById(orderId);
  }

  @Post()
  create(@Body() dto: CreateOrderDto, @Request() req): Promise<OrderDto> {
    return this.ordersService.create(dto, req.user.username);
  }

  @Put(':orderId')
  update(
    @Param('orderId', ParseIntPipe) orderId: number,
    @Body() dto: UpdateOrderDto,
    @Request() req,
  ): Promise<OrderDto> {
    return this.ordersService.update(orderId, dto, req.user.username);
  }

  @Delete(':orderId')
  @HttpCode(HttpStatus.NO_CONTENT)
  softDelete(
    @Param('orderId', ParseIntPipe) orderId: number,
    @Request() req,
  ): Promise<void> {
    return this.ordersService.softDelete(orderId, req.user.username);
  }
}
