// Generated by: neuraforge-ai / nestjs-forge
// Prompt: Build a CRUD API for Order with customerId, amount, status, notes

import {
  Entity, PrimaryGeneratedColumn, Column,
  CreateDateColumn, UpdateDateColumn,
} from 'typeorm';

@Entity('om_orders')
export class Order {
  @PrimaryGeneratedColumn()
  orderId: number;

  @Column()
  customerId: number;

  @Column('decimal', { precision: 18, scale: 4 })  // decimal — never float for money
  amount: string;  // TypeORM returns decimal as string — parse in service layer

  @Column({ length: 50, default: 'Pending' })
  status: string;

  @Column({ length: 500, nullable: true })
  notes: string | null;

  // Soft delete — never hard delete financial data
  @Column({ default: false })
  isDeleted: boolean;

  // Audit fields — mandatory on all entities
  @Column({ length: 100 })
  createdBy: string;

  @Column({ length: 100 })
  modifiedBy: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  modifiedAt: Date;
}
