// Generated by: neuraforge-ai / flutter-forge
// Prompt: Create an order list screen with pull-to-refresh and pagination

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/orders_provider.dart';
import '../widgets/order_card.dart';
import '../widgets/empty_state.dart';
import '../widgets/error_retry.dart';

class OrderListScreen extends ConsumerStatefulWidget {
  const OrderListScreen({super.key});

  @override
  ConsumerState<OrderListScreen> createState() => _OrderListScreenState();
}

class _OrderListScreenState extends ConsumerState<OrderListScreen> {
  int _page = 1;
  final _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(_onScroll);
  }

  @override
  void dispose() {
    _scrollController.dispose();  // prevent setState after dispose
    super.dispose();
  }

  void _onScroll() {
    if (_scrollController.position.pixels >=
        _scrollController.position.maxScrollExtent * 0.9) {
      _loadNextPage();
    }
  }

  void _loadNextPage() {
    final ordersAsync = ref.read(ordersProvider(page: _page));
    ordersAsync.whenData((orders) {
      if (_page < orders.totalPages) setState(() => _page++);
    });
  }

  @override
  Widget build(BuildContext context) {
    final ordersAsync = ref.watch(ordersProvider(page: _page));

    return Scaffold(
      appBar: AppBar(title: const Text('Orders')),
      body: ordersAsync.when(
        // Loading state — skeleton, not blank screen
        loading: () => ListView.builder(
          itemCount: 5,
          itemBuilder: (_, __) => const OrderCardSkeleton(),
        ),
        // Error state — message + retry
        error: (error, _) => ErrorRetry(
          message: "Couldn't load orders. Pull down to retry.",
          onRetry: () => ref.invalidate(ordersProvider),
        ),
        // Data state — formatted content
        data: (ordersPage) {
          if (ordersPage.items.isEmpty) {
            return const EmptyState(
              icon: Icons.receipt_long_outlined,
              title: 'No orders yet',
              subtitle: 'Orders will appear here once placed.',
            );
          }
          return RefreshIndicator(
            onRefresh: () async => ref.invalidate(ordersProvider),
            child: ListView.builder(
              controller: _scrollController,
              padding: const EdgeInsets.all(16),
              itemCount: ordersPage.items.length,
              itemBuilder: (context, index) => OrderCard(
                order: ordersPage.items[index],
                onTap: () => context.go('/orders/${ordersPage.items[index].orderId}'),
              ),
            ),
          );
        },
      ),
    );
  }
}
