// Generated by: neuraforge-ai / dotnet-forge
// Prompt: Build a CRUD API for Order with customerId, amount, status, notes

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Api.Models;

[Table("om_orders")]
public class Order
{
    [Key]
    public int OrderId { get; set; }

    [Required]
    public int CustomerId { get; set; }

    [Required]
    [Column(TypeName = "decimal(18,4)")]  // decimal — never float/double for money
    public decimal Amount { get; set; }

    [Required]
    [MaxLength(50)]
    public string Status { get; set; } = "Pending";

    [MaxLength(500)]
    public string? Notes { get; set; }

    // Soft delete — never hard delete financial data
    public bool IsDeleted { get; set; } = false;

    // Audit fields — mandatory on all entities
    [Required]
    [MaxLength(100)]
    public string CreatedBy { get; set; } = string.Empty;

    [Required]
    [MaxLength(100)]
    public string ModifiedBy { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime ModifiedAt { get; set; } = DateTime.UtcNow;

    // Row version for optimistic concurrency
    [Timestamp]
    public byte[]? RowVersion { get; set; }
}
