// Generated by: neuraforge-ai / dotnet-forge
// Thin controller — no business logic, delegates to service

using Api.DTOs;
using Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

[ApiController]
[Route("api/v1/orders")]   // kebab-case routes
[Authorize]
public class OrdersController : ControllerBase
{
    private readonly IOrderService _orderService;

    public OrdersController(IOrderService orderService)
    {
        _orderService = orderService;
    }

    [HttpGet]
    [ProducesResponseType(typeof(PagedResponse<OrderDto>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetAll([FromQuery] PaginationParams pagination)
    {
        var result = await _orderService.GetAllAsync(pagination).ConfigureAwait(false);
        return Ok(result);
    }

    [HttpGet("{orderId:int}")]
    [ProducesResponseType(typeof(OrderDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetById(int orderId)
    {
        var order = await _orderService.GetByIdAsync(orderId).ConfigureAwait(false);
        if (order is null) return NotFound();
        return Ok(order);
    }

    [HttpPost]
    [ProducesResponseType(typeof(OrderDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status422UnprocessableEntity)]
    public async Task<IActionResult> Create([FromBody] CreateOrderDto dto)
    {
        var createdOrder = await _orderService.CreateAsync(dto, User.Identity!.Name!).ConfigureAwait(false);
        return CreatedAtAction(nameof(GetById), new { orderId = createdOrder.OrderId }, createdOrder);
    }

    [HttpPut("{orderId:int}")]
    [ProducesResponseType(typeof(OrderDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Update(int orderId, [FromBody] UpdateOrderDto dto)
    {
        var updatedOrder = await _orderService.UpdateAsync(orderId, dto, User.Identity!.Name!).ConfigureAwait(false);
        if (updatedOrder is null) return NotFound();
        return Ok(updatedOrder);
    }

    [HttpDelete("{orderId:int}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete(int orderId)
    {
        var deleted = await _orderService.SoftDeleteAsync(orderId, User.Identity!.Name!).ConfigureAwait(false);
        if (!deleted) return NotFound();
        return NoContent();
    }
}
