// Generated by: neuraforge-ai / rn-forge
// Prompt: Create an order list screen with pull-to-refresh and pagination

import { useState, useCallback } from 'react';
import {
  FlatList, StyleSheet, View, Text,
  ActivityIndicator, RefreshControl,
} from 'react-native';
import { useOrders, ordersKeys } from './useOrders';
import { useQueryClient } from '@tanstack/react-query';
import { OrderCard } from './OrderCard';
import { EmptyState } from '../common/EmptyState';
import { ErrorRetry } from '../common/ErrorRetry';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/types';
import { colors } from '../theme/tokens'; // from get_design_tokens — never hardcode hex values

type Props = NativeStackScreenProps<RootStackParamList, 'OrderList'>;

export function OrderListScreen({ navigation }: Props) {
  const [page, setPage] = useState(1);
  const queryClient = useQueryClient();

  // React Query — never useState + useEffect for API data
  const { data, isLoading, isError, refetch } = useOrders({ page });

  const handleRefresh = useCallback(async () => {
    await queryClient.invalidateQueries({ queryKey: ordersKeys.lists() });
  }, [queryClient]);

  const handleLoadMore = useCallback(() => {
    if (data && page < data.totalPages) setPage((p) => p + 1);
  }, [data, page]);

  // Loading state
  if (isLoading && page === 1) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={colors.brand.primary} />
      </View>
    );
  }

  // Error state
  if (isError) {
    return <ErrorRetry message="Couldn't load orders." onRetry={refetch} />;
  }

  // Empty state
  if (!data?.items.length) {
    return <EmptyState icon="receipt" title="No orders yet" />;
  }

  // Data state
  return (
    <FlatList
      data={data.items}
      keyExtractor={(item) => String(item.orderId)}
      renderItem={({ item }) => (
        <OrderCard
          order={item}
          onPress={() => navigation.navigate('OrderDetail', { orderId: item.orderId })}
        />
      )}
      contentContainerStyle={styles.list}
      refreshControl={
        <RefreshControl refreshing={isLoading} onRefresh={handleRefresh} />
      }
      onEndReached={handleLoadMore}
      onEndReachedThreshold={0.3}
      ListFooterComponent={
        isLoading && page > 1 ? <ActivityIndicator style={styles.footer} /> : null
      }
    />
  );
}

const styles = StyleSheet.create({
  list: { padding: 16 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  footer: { paddingVertical: 16 },
});
