// Generated by: neuraforge-ai / react-forge
// Prompt: Create an order list screen with search, filters, and pagination

import { useState } from 'react';
import { useOrders } from './useOrders';
import { OrderCard } from './OrderCard';
import { Skeleton } from '../common/Skeleton';
import { EmptyState } from '../common/EmptyState';
import { ErrorRetry } from '../common/ErrorRetry';
import { Pagination } from '../common/Pagination';

// React Query for data fetching — never useState + useEffect
export function OrderList() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<string | undefined>();

  const { data, isLoading, isError, refetch } = useOrders({ page, search, status });

  // Loading state — skeleton matching content layout
  if (isLoading) {
    return (
      <div className="order-list">
        {Array.from({ length: 5 }).map((_, i) => (
          <Skeleton key={i} height={80} />
        ))}
      </div>
    );
  }

  // Error state — user-friendly message + retry
  if (isError) {
    return (
      <ErrorRetry
        message="Couldn't load orders. Check your connection and try again."
        onRetry={refetch}
      />
    );
  }

  // Empty state — helpful message + action
  if (data?.items.length === 0) {
    return (
      <EmptyState
        icon="receipt"
        title="No orders yet"
        subtitle="Orders will appear here once customers place them."
      />
    );
  }

  // Data state — formatted content
  return (
    <div className="order-list">
      <div className="order-list__filters">
        <input
          type="search"
          placeholder="Search by customer or order ID..."
          value={search}
          onChange={(e) => { setSearch(e.target.value); setPage(1); }}
          className="order-list__search"
        />
        <select
          value={status ?? ''}
          onChange={(e) => { setStatus(e.target.value || undefined); setPage(1); }}
        >
          <option value="">All statuses</option>
          <option value="Pending">Pending</option>
          <option value="Processing">Processing</option>
          <option value="Completed">Completed</option>
          <option value="Cancelled">Cancelled</option>
        </select>
      </div>

      <div className="order-list__items">
        {data?.items.map((order) => (
          <OrderCard key={order.orderId} order={order} />
        ))}
      </div>

      <Pagination
        currentPage={page}
        totalPages={data?.totalPages ?? 1}
        onPageChange={setPage}
      />
    </div>
  );
}
