// Generated by: neuraforge-ai / react-forge
// Query options pattern — hierarchical keys, typed, reusable

import { useQuery } from '@tanstack/react-query';
import { ordersService } from './orders.service';
import type { PaginatedResponse } from '../common/types';
import type { Order } from './order.types';

interface UseOrdersParams {
  page: number;
  search?: string;
  status?: string;
}

// Query key factory — hierarchical, invalidation-friendly
export const ordersKeys = {
  all: ['orders'] as const,
  lists: () => [...ordersKeys.all, 'list'] as const,
  list: (params: UseOrdersParams) => [...ordersKeys.lists(), params] as const,
  detail: (orderId: number) => [...ordersKeys.all, 'detail', orderId] as const,
};

export function useOrders(params: UseOrdersParams) {
  return useQuery({
    queryKey: ordersKeys.list(params),
    queryFn: () => ordersService.getAll(params),
    staleTime: 5 * 60 * 1000,   // 5 minutes — list data doesn't change frequently
    placeholderData: (prev) => prev, // keep previous page visible while loading next
  });
}

export function useOrder(orderId: number) {
  return useQuery({
    queryKey: ordersKeys.detail(orderId),
    queryFn: () => ordersService.getById(orderId),
    staleTime: 10 * 60 * 1000,  // 10 minutes — detail data is more stable
    enabled: orderId > 0,
  });
}
