# Generated by: neuraforge-ai / django-forge
# Prompt: Build a CRUD API for Order with customerId, amount, status, notes

from decimal import Decimal
from django.db import models
from rest_framework import serializers, status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from .models import Order
from .serializers import OrderSerializer, CreateOrderSerializer
from ..common.pagination import StandardPagination


class OrderViewSet(ModelViewSet):
    """
    CRUD endpoints for orders.
    Soft deletes — never hard deletes.
    """
    permission_classes = [IsAuthenticated]
    pagination_class = StandardPagination
    http_method_names = ['get', 'post', 'put', 'delete']

    def get_queryset(self):
        # Exclude soft-deleted records
        qs = Order.objects.filter(is_deleted=False).order_by('-created_at')

        # Optional filters
        customer_id = self.request.query_params.get('customerId')
        order_status = self.request.query_params.get('status')
        if customer_id:
            qs = qs.filter(customer_id=customer_id)
        if order_status:
            qs = qs.filter(status=order_status)
        return qs

    def get_serializer_class(self):
        if self.action == 'create':
            return CreateOrderSerializer
        return OrderSerializer

    def perform_create(self, serializer):
        serializer.save(
            created_by=self.request.user.username,
            modified_by=self.request.user.username,
        )

    def perform_update(self, serializer):
        serializer.save(modified_by=self.request.user.username)

    def destroy(self, request, *args, **kwargs):
        # Soft delete — set flag, never remove the row
        order = self.get_object()
        order.is_deleted = True
        order.modified_by = request.user.username
        order.save(update_fields=['is_deleted', 'modified_by', 'modified_at'])
        return Response(status=status.HTTP_204_NO_CONTENT)
