// Generated by: neuraforge-ai / spring-forge
// Thin controller — delegates to service, no business logic here

package com.example.api.orders;

import com.example.api.common.PagedResponse;
import com.example.api.common.PaginationParams;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/orders")
@RequiredArgsConstructor
public class OrderController {

    private final OrderService orderService;

    @GetMapping
    public ResponseEntity<PagedResponse<OrderDto>> getAll(PaginationParams pagination) {
        return ResponseEntity.ok(orderService.getAll(pagination));
    }

    @GetMapping("/{orderId}")
    public ResponseEntity<OrderDto> getById(@PathVariable Long orderId) {
        return ResponseEntity.ok(orderService.getById(orderId));
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public ResponseEntity<OrderDto> create(
            @Valid @RequestBody CreateOrderDto dto,
            @AuthenticationPrincipal UserDetails user) {
        OrderDto created = orderService.create(dto, user.getUsername());
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @PutMapping("/{orderId}")
    public ResponseEntity<OrderDto> update(
            @PathVariable Long orderId,
            @Valid @RequestBody UpdateOrderDto dto,
            @AuthenticationPrincipal UserDetails user) {
        return ResponseEntity.ok(orderService.update(orderId, dto, user.getUsername()));
    }

    @DeleteMapping("/{orderId}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public ResponseEntity<Void> delete(
            @PathVariable Long orderId,
            @AuthenticationPrincipal UserDetails user) {
        orderService.softDelete(orderId, user.getUsername());  // soft delete
        return ResponseEntity.noContent().build();
    }
}
